### PR TITLE
add some functions

### PR DESCRIPTION
**Pull request by chessai**

### CODE REVIEW

**Comment by andrewthad** [comment]
I’ve not checked that the implementations are correct, although I assume they are. All of these seem reasonable, and I can understand why they would be desired except for `anyBut`. I feel like you would always want to case on the resulting byte anyway, but if your doing that, why not just call fail in an arm of the case statement? It seems useful if you are going to treat all the passing non-rejected bytes homogeneously, but I cannot think of a parsing situation where that happens. Do you have such a situation in mind?

**Comment by chessai** [comment]
@andrewthad i do not, but it is included in attoparsec, which is why i thought it might be useful here. your reasoning makes sense, but bos doesn't include things he thinks won't be useful, so maybe there is some reason.

**Comment by chessai** [comment]
I could imagine using it most to just discard the result actually, `void $ anyBut 10` or something

**Comment by andrewthad** [comment]
> it is included in attoparsec

I don't see it in `attoparsec` or in `megaparsec` for that matter. Perhaps there's another parsing library you saw this in.

> I could imagine using it most to just discard the result actually, void $ anyBut 10 or something

Unconditionally throwing away the result byte is a way to get homogenous treatment of it. However, I'm not convinced that this situation would ever arise in practice. There is almost never just one unacceptable byte. It's usually a whole class of them. And there `satisfy` gets the job done cleanly.

Also, I just noticed that `satisfyWith` has the wrong return type. It should be `a` instead of `Word8`.

**Comment by chessai** [comment]
https://hackage.haskell.org/package/attoparsec-0.13.2.3/docs/Data-Attoparsec-ByteString.html#v:notWord8

**Comment by chessai** [comment]
addressed concerns

**Pull request merged**
